In [2]:
import numpy as np

In [3]:
T = 7.0
dt = 1e-3
N = int(T / dt)
rng = np.random.default_rng(0)

num_sections = 10       # number of pieces [0, N] is split into for phi(t)

_phi_cache = {}
def phi(t, num_sections):
    # same random phase for every t falling in the same one of `num_sections`
    # equal-width sections of the index range [0, N]; different phase across sections
    section_idx = min(int((t / dt) * num_sections / N), num_sections - 1)
    if section_idx not in _phi_cache:
        _phi_cache[section_idx] = np.random.default_rng(section_idx).uniform(0.0, 2 * np.pi)
    return _phi_cache[section_idx]

for t in [0, 0.5, 1, 1.2, 6.2, 6.5, 6.9]:
    print(f"phi({t:.3f}) = {phi(t, num_sections):.3f}")

phi(0.000) = 4.002
phi(0.500) = 4.002
phi(1.000) = 3.216
phi(1.200) = 3.216
phi(6.200) = 2.054
phi(6.500) = 5.468
phi(6.900) = 5.468


In [6]:
print(_phi_cache[0])

4.002148315014479


In [2]:
import numpy as np

In [4]:
rng = np.random.default_rng(0)
for i in range(3):
    a = rng.uniform(0, 10, 5)
    print(a)

[6.36961687 2.69786714 0.40973524 0.16527636 8.13270239]
[9.12755577 6.06635776 7.29496561 5.43624991 9.35072424]
[8.15853554 0.027385   8.57404277 0.33585575 7.29655446]
